# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Enable 32bit and install wine/mono
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt update && sudo apt install wine wine32 mono-devel -y
    - uses: actions/checkout@v4
    - uses: actions/checkout@master
      with:
        repository: Yuvix25/Electron.NET
        ref: ReHUD/main
        path: ./electronnet
    - name: Check paths
      run: ls ./electronnet
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.4
      with: 
        node-version: 22.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install npm packages
      run: npm i
    - name: Install electronize
      run: dotnet tool install ElectronNET.CLI -g
    - name: Build application
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: Installer
        path: ./bin/Desktop/ReHUD*.exe
